name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests with Allure Report
      env:
        STANDARD_USER_USERNAME: ${{ secrets.STANDARD_USER_USERNAME }}
        STANDARD_USER_PASSWORD: ${{ secrets.STANDARD_USER_PASSWORD }}
        LOCKED_OUT_USER_USERNAME: ${{ secrets.LOCKED_OUT_USER_USERNAME }}
        LOCKED_OUT_USER_PASSWORD: ${{ secrets.LOCKED_OUT_USER_PASSWORD }}
        PROBLEM_USER_USERNAME: ${{ secrets.PROBLEM_USER_USERNAME }}
        PROBLEM_USER_PASSWORD: ${{ secrets.PROBLEM_USER_PASSWORD }}
        PERFORMANCE_GLITCH_USER_USERNAME: ${{ secrets.PERFORMANCE_GLITCH_USER_USERNAME }}
        PERFORMANCE_GLITCH_USER_PASSWORD: ${{ secrets.PERFORMANCE_GLITCH_USER_PASSWORD }}
        ERROR_USER_USERNAME: ${{ secrets.ERROR_USER_USERNAME }}
        ERROR_USER_PASSWORD: ${{ secrets.ERROR_USER_PASSWORD }}
        VISUAL_USER_USERNAME: ${{ secrets.VISUAL_USER_USERNAME }}
        VISUAL_USER_PASSWORD: ${{ secrets.VISUAL_USER_PASSWORD }}
      run: |
        npx playwright test --reporter=line,allure-playwright
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30